"""empty message

Revision ID: 3f29297b3bef
Revises: 0625f58e191e
Create Date: 2026-02-23 23:00:14.198483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f29297b3bef'
down_revision = '0625f58e191e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_images', schema=None) as batch_op:
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
