"""empty message

Revision ID: b1801a26ec7f
Revises: c15bb94a2b9a
Create Date: 2026-03-13 19:21:49.574740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1801a26ec7f'
down_revision = 'c15bb94a2b9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=300), nullable=True))

    with op.batch_alter_table('business_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_request', schema=None) as batch_op:
        batch_op.drop_column('logo_url')

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
